import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { io } from "socket.io-client";

const socket = io(process.env.NODE_ENV === 'production' ? "https://bb-pointing-poker.herokuapp.com" : 'http://localhost:8080', {
  withCredentials: true,
});

export default function Home() {
  return (
<>
      <Head>
        <title>ButcherBox Pointing Poker</title>
        <meta name="description" content="Generated by MATT BEAL" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.header}>ButcherBox Pointing Poker!</h1>
        <label className={styles.inputLabel} htmlFor="room-number-input"
          >Enter room number to join or create a pointing session
        </label>
        <div className={styles.column}>
          <div>
            <input  type="text" id="room-number-input" />
            <button>Join Room</button>
          </div>
          <p className={styles.largeText}>OR</p>
          <button>Create new room</button>
        </div>
      </main>
      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        </a> */}
      </footer>
      </>
  )
}
